[project]
site_name = "reCocina"
site_description = "Recetario de cocina casera"
site_author = "reCocina"
docs_dir = "docs"
copyright = "© 2024 reCocina"
extra_css = [
    "assets/stylesheets/extra.css",
    "assets/stylesheets/print.css"
]
extra_javascript = [
    "assets/javascripts/daily-recipe.js",
]

nav = [
    { "Entrada" = "index.md" },
    { "Etiquetas" = "etiquetas.md" },
    { "Fuentes" = "fuentes.md" },
    { "Aperitivos" = [
        "recetas/almogrote-gomero.md",
        "recetas/ensaladilla-de-papas-con-lacon-y-huevo.md",
        "recetas/fajitas-de-soja-texturizada.md",
    ] },
    { "Arroz" = [
        "recetas/arroz-a-banda-con-sepia.md",
        "recetas/arroz-con-pollo-y-gambas.md",
        "recetas/curry-de-verduras-con-gambas.md",
        "recetas/salmon-teriyaki-con-arroz.md",
    ] },
    { "Pasta" = [
        "recetas/espagueti-carbonara.md",
        "recetas/pasta-con-cherry.md",
        "recetas/pasta-con-langostinos.md",
        "recetas/pasta-con-setas-a-la-foie.md",
    ] },
    { "Pollo" = [
        "recetas/cuscus-de-pollo-y-verduras.md",
        "recetas/pastel-de-calabaza-y-pollo.md",
        "recetas/pechuga-cocida-con-champinones.md",
        "recetas/pechuga-a-la-miel-y-mostaza.md",
        "recetas/pollo-caprese-al-pesto.md",
    ] },
    { "Carne" = [
        "recetas/cabra-guisada.md",
        "recetas/cerdo-agridulce.md",
        "recetas/estofado-de-ternera.md",
        "recetas/solomillo-de-cerdo-con-papas-y-frutos-secos.md",
    ] },
    { "Pescado y Mariscos" = [
        "recetas/calamares-rellenos-de-carne.md",
        "recetas/guiso-de-calamares-con-alcachofas-y-albondigas.md",
        "recetas/marmitako-de-atun.md",
    ] },
    { "Postres" = [
        "recetas/brownie-coulant.md",
        "recetas/peras-al-vino.md",
        "recetas/sopa-de-melon.md",
    ] },
    { "Salsas" = [
        "recetas/bechamel.md",
        "recetas/mojo-de-cilantro.md",
        "recetas/salsa-barbacoa.md",
        "recetas/salsa-curry.md",
        "recetas/salsa-pesto.md",
        "recetas/salsa-teriyaki.md",
    ] },
    { "Sopas y Cremas" = [
        "recetas/crema-de-champinones.md",
        "recetas/crema-de-quinoa-y-calabaza.md",
        "recetas/sopa-de-ajo.md",
        "recetas/sopa-de-verduras-con-huevo.md",
        "recetas/sopa-minestrone.md",
    ] },
    { "Verduras, Legumbres y Potajes" = [
        "recetas/musabaha.md",
        "recetas/potaje-de-berros.md",
        "recetas/potaje-de-vigilia.md",
    ] },
]

[project.theme]
variant = "classic"
language = "es"
custom_dir = "theme"
favicon = "assets/images/favicon.ico"
logo = "assets/images/logo.svg"
features = [
    "navigation.sections",
    "navigation.top",
    "search.highlight",
    "search.suggest",
    "content.code.copy",
]


[[project.theme.palette]]
scheme = "light"
primary = "custom"
accent = "custom"
toggle.icon = "fontawesome/regular/sun"
toggle.name = "Cambiar a modo oscuro"

[[project.theme.palette]]
scheme = "slate"
primary = "custom"
accent = "custom"
toggle.icon = "fontawesome/regular/moon"
toggle.name = "Cambiar a modo claro"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/isidro-rodriguez/recocina"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://www.python.org"

[[project.extra.social]]
icon = "fontawesome/brands/markdown"
link = "https://daringfireball.net/projects/markdown/"

[project.extra.tags]
Batidora = "mixer"
Horno = "oven"
Mortero = "mortar"
Paellera = "pan"
Wok = "pan"
Pescetariano = "fish"
Vegano = "vegan"
Vegetariano = "vegan"

[project.theme.icon.tag]
mixer = "mixer"
oven = "oven"
mortar = "mortar"
pan = "pan"
fish = "fish"
vegan = "vegan"

[project.markdown_extensions]
abbr = { }
admonition = { }
attr_list = { }
def_list = { }
footnotes = { }
md_in_html = { }
pymdownx.arithmatex.generic = false
pymdownx.betterem = { }
pymdownx.details = { }
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight = { }
pymdownx.superfences = { }
pymdownx.tasklist = { }
